### ISSUE TITLE
doesn't find rows to iterate with default craigslist settings (error on line 19)

### ISSUE THREAD

**Issue by atsepkov** [gjreda/craigslist-checker#2]
This seems to break for me due to craigslist defaulting to "thumbnails" layout and the script assuming a list. Unfortunately, it looks like switching to list layout can't be done via url parameter itself (looks like the list switch is done via JavaScript and then uses a cookie to track the preference).

**Comment by gjreda** [comment]
Craigslist changed the default layout since this was written a while back. I don't intend on fixing this as this repo was meant for sharing the code with others, not necessarily turning into an on-going project.
